name: dreams_dictionary
description: Flutter dreams dictionary application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  floor: ^1.4.2
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  riverpod_generator: ^2.3.3
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/dreams_dictionary.json